wagtail/contrib/forms/urls.py
from django.conf.urls import url

from wagtail.contrib.forms.views import (
    DeleteSubmissionsView, FormPagesListView, get_submissions_list_view)

app_name = 'wagtailforms'
urlpatterns = [
    url(r'^$', FormPagesListView.as_view(), name='index'),
    url(r'^submissions/(?P<page_id>\d+)/$', get_submissions_list_view, name='list_submissions'),
    url(r'^submissions/(?P<page_id>\d+)/delete/$', DeleteSubmissionsView.as_view(), name='delete_submissions')
]

wagtail/contrib/forms/templates/wagtailforms/confirm_delete.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans with title=page.title %}Delete form data {{ title }}{% endblocktrans %}{% endblock %}
{% block bodyclass %}menu-explorer{% endblock %}

{% block content %}
    {% trans "Delete form data" as del_str %}
    {% include "wagtailadmin/shared/header.html" with title=del_str subtitle=page.title icon="doc-empty-inverse" %}

    <div class="nice-padding">
        <p>
            {% blocktrans count counter=submissions.count %}
                Are you sure you want to delete this form submission?
            {% plural %}
                Are you sure you want to delete these form submissions?
            {% endblocktrans %}
        </p>
        <form action="{% url 'wagtailforms:delete_submissions' page.id %}?{{ request.GET.urlencode }}" method="POST">
            {% csrf_token %}
            <input type="submit" value="{% trans 'Delete' %}" class="button serious">
        </form>
    </div>
{% endblock %}

wagtail/contrib/forms/templates/wagtailforms/index.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% trans "Forms" %}{% endblock %}
{% block content %}
    {% trans "Forms" as forms_str %}
    {% trans "Pages" as select_form_str %}
    {% include "wagtailadmin/shared/header.html" with title=forms_str subtitle=select_form_str icon="form" %}

    <div class="nice-padding">
        <div id="form-results" class="forms">
            {% include "wagtailforms/results_forms.html" %}
        </div>
    </div>
{% endblock %}

wagtail/contrib/forms/templates/wagtailforms/index_submissions.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans with form_title=form_page.title|capfirst %}Submissions of {{ form_title }}{% endblocktrans %}{% endblock %}
{% block extra_js %}
    {{ block.super }}

    <script>
        $.fn.datetimepicker.defaults.i18n.wagtail_custom_locale = {
            months: wagtailConfig.STRINGS.MONTHS,
            dayOfWeek: wagtailConfig.STRINGS.WEEKDAYS,
            dayOfWeekShort: wagtailConfig.STRINGS.WEEKDAYS_SHORT,
        }
        $.datetimepicker.setLocale('wagtail_custom_locale');

        $(function() {
            $('#id_date_from').datetimepicker({
                timepicker: false,
                format: 'Y-m-d',
            });
            $('#id_date_to').datetimepicker({
                timepicker: false,
                format: 'Y-m-d',
            });

            var selectAllCheckbox = document.getElementById('select-all');
            var deleteButton = document.getElementById('delete-submissions');
            var selectedSubmissions = {};

            function updateActions() {
                var submissionCheckboxes = $('input[type=checkbox].select-submission');
                var someSubmissionsSelected = submissionCheckboxes.is(':checked');
                var everySubmissionSelected = !submissionCheckboxes.is(':not(:checked)');

                // Select all box state
                if (everySubmissionSelected) {
                    // Every submission has been selected
                    selectAllCheckbox.checked = true;
                    selectAllCheckbox.indeterminate = false;
                } else if (someSubmissionsSelected) {
                    // At least one, but not all submissions have been selected
                    selectAllCheckbox.checked = false;
                    selectAllCheckbox.indeterminate = true;
                } else {
                    // No submissions have been selected
                    selectAllCheckbox.checked = false;
                    selectAllCheckbox.indeterminate = false;
                }

                // Delete button state
                if (someSubmissionsSelected) {
                    deleteButton.classList.remove('disabled')
                    deleteButton.style.visibility = "visible";
                } else {
                    deleteButton.classList.add('disabled')
                    deleteButton.style.visibility = "hidden";
                }
            }


            // Event handlers

            $(selectAllCheckbox).on('change', function() {
                let checked = this.checked;

                // Update checkbox states
                $('input[type=checkbox].select-submission').each(function() {
                    this.checked = checked;
                });

                updateActions();
            });

            $('input[type=checkbox].select-submission').on('change', function() {
                updateActions();
            });

            // initial call to updateActions to bring delete button state in sync with checkboxes
            // in the case that some checkboxes are pre-checked (which will be the case in some
            // browsers when using the back button)
            updateActions();
        });
    </script>
{% endblock %}
{% block content %}
    <header class="nice-padding" role="banner">
        <form action="" method="get" novalidate>
            <div class="row">
                <div class="left">
                    <div class="col header-title">
                        <h1 class="icon icon-form">
                        {% blocktrans with form_title=form_page.title|capfirst %}Form data <span>{{ form_title }}</span>{% endblocktrans %}
                        </h1>
                    </div>
                    <div class="col search-bar">
                        <ul class="fields row rowflush">
                            {% for field in select_date_form %}
                                {% include "wagtailadmin/shared/field_as_li.html" with field=field field_classes="field-small" li_classes="col4" %}
                            {% endfor %}
                            <li class="submit col2">
                                <button name="action" value="filter" class="button button-filter">{% trans 'Filter' %}</button>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="right">
                   <button name="action" value="CSV" class="button bicolor icon icon-download">{% trans 'Download CSV' %}</button>
                </div>
            </div>
        </form>
    </header>
    <div class="nice-padding">
        {% if submissions %}
            <form action="{% url 'wagtailforms:delete_submissions' form_page.id %}" method="get">
                {% include "wagtailforms/list_submissions.html" %}
                {% include "wagtailadmin/shared/pagination_nav.html" with items=page_obj %}
            </form>
        {% else %}
            <p class="no-results-message">{% blocktrans with title=form_page.title %}There have been no submissions of the '{{ title }}' form.{% endblocktrans %}</p>
        {% endif %}
    </div>
{% endblock %}

wagtail/contrib/forms/templates/wagtailforms/list_forms.html
{% load i18n %}
<table class="listing">
    <col width="50%"/>
    <col width="50%"/>
    <thead>
        <tr>
            <th class="title">{% trans "Title" %}</th>
            <th class="type">{% trans "Origin" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for fp in form_pages %}
            <tr>
                <td class="title">
                    <div class="title-wrapper"><a href="{% url 'wagtailforms:list_submissions' fp.id %}">{{ fp|capfirst }}</a></div>
                </td>
                <td class="type">
                    <small><a href="{% url 'wagtailadmin_pages:edit' fp.id %}" class="nolink">{{ fp.content_type.name |capfirst }} ({{ fp.content_type.app_label }}.{{ fp.content_type.model }})</a></small>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

wagtail/contrib/forms/templates/wagtailforms/list_submissions.html
{% load i18n %}
<div class="overflow">
<table class="listing">
    <col />
    <col />
    <col />
    <thead>
        <tr>
            <th colspan="{{ data_headings|length|add:1 }}">
                <button class="button no" id="delete-submissions" style="visibility: hidden">{% trans "Delete selected submissions" %}</button>
            </th>
        </tr>
        <tr>
            <th><input type="checkbox" id="select-all" /></th>
            {% for heading in data_headings %}
                <th id="{{ heading.name }}" class="{% if heading.order %}ordered {{ heading.order }}{% endif %}">
                  {% if heading.order %}<a href="?order_by={% if heading.order == 'ascending' %}-{% endif %}{{ heading.name }}">{{ heading.label }}</a>{% else %}{{ heading.label }}{% endif %}
                </th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for row in data_rows %}
            <tr>
                <td>
                    <input type="checkbox" name="selected-submissions" class="select-submission" value="{{ row.model_id }}" />
                </td>
                {% for cell in row.fields %}
                    <td>
                        {{ cell }}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>

wagtail/contrib/forms/templates/wagtailforms/results_forms.html
{% load i18n %}
{% if form_pages %}
    {% include "wagtailforms/list_forms.html" %}

    {% include "wagtailadmin/shared/pagination_nav.html" with items=page_obj linkurl="wagtailforms:index" %}
{% else %}
    <p>{% trans "No form pages have been created." %}</p>
{% endif %}